cask "font-maple-mini" do
  version "7.9.7"
  sha256 "97931da3e3f459cd7ffb3fd6b53ba08ceafe986b9b80dc0d9d4a500045c71904"

  url "https://github.com/lecodeski/homebrew-maple-font/releases/download/v-latest/MapleMini-NF-unhinted.zip"
  name "Maple Mini NF"
  desc "Forked and re-configured build of Maple Mono with Nerd Font icons"
  homepage "https://github.com/lecodeski/homebrew-maple-font"

  font "MapleMini-NF-Bold.ttf"
  font "MapleMini-NF-BoldItalic.ttf"
  font "MapleMini-NF-ExtraBold.ttf"
  font "MapleMini-NF-ExtraBoldItalic.ttf"
  font "MapleMini-NF-ExtraLight.ttf"
  font "MapleMini-NF-ExtraLightItalic.ttf"
  font "MapleMini-NF-Italic.ttf"
  font "MapleMini-NF-Light.ttf"
  font "MapleMini-NF-LightItalic.ttf"
  font "MapleMini-NF-Medium.ttf"
  font "MapleMini-NF-MediumItalic.ttf"
  font "MapleMini-NF-Regular.ttf"
  font "MapleMini-NF-SemiBold.ttf"
  font "MapleMini-NF-SemiBoldItalic.ttf"
  font "MapleMini-NF-Thin.ttf"
  font "MapleMini-NF-ThinItalic.ttf"
end
